build:
  stage: build
  tags:
    - shared
  variables: 
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"


  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker


  # before_script:
  #   -  groupadd -g 998 docker
  #   -  cat /etc/group

  # Jobs are ran independently from each other, so build and scan needs to be in a single job.

  script:
    - |
      wget --header "Authorization: Basic $(echo -n $PCC_USER:$PCC_PASS | base64 | tr -d '\n')" "$PCC_CONSOLE_URL/api/v1/util/twistcli"
      chmod a+x ./twistcli
      docker build -t $IMAGE_NAME .
      ./twistcli images scan --docker-address http://docker:2375 --address $PCC_CONSOLE_URL --user $PCC_USER --password $PCC_PASS --details $IMAGE_NAME
