build:
  stage: build
  tags:
    - shared
  variables: 
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: "twistlock-scan-sample"


  image: docker:18.09
  services:
    - name: docker:18.09-dind
      alias: docker
      entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]

  # Jobs are ran independently from each other, so build and scan needs to be in a single job.

  script:
    - |
      wget --header "Authorization: Basic $(echo -n $PCC_USER:$PCC_PASS | base64 | tr -d '\n')" "$PCC_CONSOLE_URL/api/v1/util/twistcli"
      chmod a+x ./twistcli
      docker build -t $IMAGE_NAME .
      ./twistcli images scan --docker-address $DOCKER_HOST --address $PCC_CONSOLE_URL --user $PCC_USER --password $PCC_PASS --details $IMAGE_NAME
